fix(icurve swap): modified wrong function signature in ICurveSwap.sol
Opty-Fi/defi-legos pull request #45
Opened 2022-01-19 13:25 UTC by mariogutval

Fixes #44 

In ICurveSwap.sol, this is one of the functions: 

`function calc_token_amount(uint256[] calldata amountsIn, bool deposit) external view returns (uint256);`

However, that signature is not valid for any swap pool. Instead, the first argument should be a fixed-length array, so we should have multiple functions:

`function calc_token_amount(uint256[2] calldata amountsIn, bool deposit) external view returns (uint256);`
`function calc_token_amount(uint256[3] calldata amountsIn, bool deposit) external view returns (uint256);`
`function calc_token_amount(uint256[4] calldata amountsIn, bool deposit) external view returns (uint256);`

#### PR Checklist

- [ ] Tests

2022-01-19 13:27 UTC, uwe commented
Does it work like this, or would we need 3 files? I think other signatures also depend on the number of coins (2 .. 4).

2022-01-19 13:30 UTC, mariogutval commented
> Does it work like this, or would we need 3 files? I think other signatures also depend on the number of coins (2 .. 4).

It works like this, we don't need any other file

2022-01-19 17:55 UTC, dhruvinparikh requested changes
- [x] Update ABI as well

2022-01-21 15:30 UTC, dhruvinparikh approved these changes

2022-01-21 18:05 UTC, deepcrazy approved these changes

2022-01-21 18:06 UTC, merged