feat(sushiswap polygon): added pools data and interfaces for sushiswa…
Opty-Fi/defi-legos pull request #47
Opened 2022-02-04 14:05 UTC by mariogutval

#### PR Checklist

- [ ] Tests

2022-02-04 19:16 UTC, dhruvinparikh requested changes

2022-02-04 19:16 UTC, dhruvinparikh commented on src/polygon/sushiswap/contracts.ts
> +  "sushi-wmatic-weth": {
- [ ] Keep all pools under `pools` key.

2022-02-04 19:17 UTC, dhruvinparikh commented on src/polygon/sushiswap/contracts.ts
> +  "sushi-wmatic-weth": {
@mariogutval checks are failing

2022-02-07 23:27 UTC, deepcrazy approved these changes

2022-02-08 18:37 UTC, dhruvinparikh approved these changes

2022-02-08 19:02 UTC, leodinh approved these changes

2022-02-08 19:05 UTC, merged