feat/aave-avalanche
Opty-Fi/defi-legos pull request #54
Opened 2022-04-12 03:00 UTC by leodinh

2022-04-12 18:22 UTC, deepcrazy approved these changes

2022-04-12 18:23 UTC, deepcrazy commented
- Looks fine. But Linting is failing. Please fix it.

2022-04-12 19:51 UTC, deepcrazy approved these changes

2022-04-13 00:58 UTC, dhruvinparikh requested changes
- [x] Curate all the token addresses of avalanche like [this](https://github.com/Opty-Fi/defi-legos/tree/release-v0.1/src/ethereum/tokens) (feel free to export all avalanche tokens from `avalanche/tokens/index.ts`)
- [x] Export tokens, pools and  protocols of avalanche like [this](https://github.com/Opty-Fi/defi-legos/blob/release-v0.1/src/ethereum/index.ts) 
- [ ] Export * of avalanche like [this](https://github.com/Opty-Fi/defi-legos/blob/release-v0.1/src/index.ts)

2022-04-13 00:59 UTC, dhruvinparikh commented
> * [ ]  Curate all the token addresses of avalanche like [this](https://github.com/Opty-Fi/defi-legos/tree/release-v0.1/src/ethereum/tokens) (feel free to export all avalanche tokens from `avalanche/tokens/index.ts`)
> * [ ]  Export tokens, pools and  protocols of avalanche like [this](https://github.com/Opty-Fi/defi-legos/blob/release-v0.1/src/ethereum/index.ts)
> * [ ]  Export * of avalanche like [this](https://github.com/Opty-Fi/defi-legos/blob/release-v0.1/src/index.ts)

.

2022-04-13 06:02 UTC, dhruvinparikh requested changes

2022-04-13 06:02 UTC, dhruvinparikh commented on src/avalanche/tokens/index.ts
> +  PLAIN_TOKENS,
- [ ] Include aTokens as well. Feel free to follow this approach - https://github.com/Opty-Fi/defi-legos/blob/release-v0.1/src/polygon/tokens/index.ts (all tokens are curated)

2022-04-13 06:02 UTC, dhruvinparikh commented on src/avalanche/tokens/index.ts
> +import PLAIN_TOKENS from "./plain_etokens";
```suggestion
import PLAIN_TOKENS from "./plain_tokens";
```

2022-04-19 15:08 UTC, dhruvinparikh approved these changes

2022-04-19 15:08 UTC, merged